# reference
genome:
  # reference size use by MACS
  size: hs
  fasta: /share/references/hg38/fasta/hg38.fa
  bwa_index: /share/references/hg38/bwa_index/hg38.fa
  # sorted blacklist in bed format
  blacklist: /share/references/hg38/blacklist/hg38.blacklist.sorted.bed
  # txdb export from Bioconductor GenomicFeatures package
  txdb: /share/references/hg38/txdb/ucsc-hg38-knowgene.sqlite

# adapter fasta file, comment this line will use Nextera adapter comes with dapipe
adapter: /home/andy/Projects/dapipe/src/dapipe/resources/adapter.fa

# output plots formats
plot_formats:
  - pdf
  - png

# workspace for all jobs to run the pipeline
# all of your output will be place in this dir
workspace: /path/to/workspace

# samples info
samples:
  sample1_rep1:
    fastq:
      lib1:
        fq1: /path/to/sample1_rep1/lib1/read_1.fastq.gz
        fq2: /path/to/sample1_rep1/lib1/read_2.fastq.gz
    meta:
      cell: sample1
      rep: rep1
      group: group1
  sample1_rep2:
    fastq:
      lib1:
        fq1: /path/to/sample1_rep2/lib1/read_1.fastq.gz
        fq2: /path/to/sample1_rep2/lib1/read_2.fastq.gz
    meta:
      cell: sample1
      rep: rep2
      group: group1
  sample2_rep1:
    fastq:
      lib1:
        fq1: /path/to/sample2_rep1/lib1/read_1.fastq.gz
        fq2: /path/to/sample2_rep1/lib1/read_2.fastq.gz
    meta:
      cell: sample2
      rep: rep1
      group: group2
  sample2_rep2:
    fastq:
      lib1:
        fq1: /path/to/sample2_rep2/lib1/read_1.fastq.gz
        fq2: /path/to/sample2_rep2/lib1/read_2.fastq.gz
    meta:
      cell: sample2
      rep: rep2
      group: group1

# comparisons
comparisons:
  group1_vs_group2:
    condition: group
    numerator: group1
    denominator: group2
